import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
String.prototype.isEmail = function () {
  let mailRegex = /(\w|_|-)+@(\w|.)+/;
  return mailRegex.test(this)
}
String.prototype.isValidName = function () {
  return !this.trim().includes(" ");
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
